import { useState } from 'react'
import { cloud, finishRecovery, syncNow, useCloud } from './cloud'
import { currentOwner, persistEvents, readEvents } from './store'
export default function Account(){
  const info=useCloud(),[mode,setMode]=useState<'login'|'signup'|'reset'>('login'),[email,setEmail]=useState(''),[password,setPassword]=useState(''),[message,setMessage]=useState(''),[busy,setBusy]=useState(false)
  async function signout(){if(!cloud)return;const {error}=await cloud.auth.signOut();if(error)setMessage(error.message)}
  async function submit(e:React.FormEvent){e.preventDefault();if(!cloud||busy)return;setBusy(true);setMessage('');try{
    if(info.recovering){const {error}=await cloud.auth.updateUser({password});if(error)throw error;finishRecovery();setPassword('');setMessage('Пароль обновлён.')}
    else if(mode==='login'){const {error}=await cloud.auth.signInWithPassword({email,password});if(error)throw error;setPassword('')}
    else if(mode==='signup'){const {error}=await cloud.auth.signUp({email,password,options:{emailRedirectTo:window.location.origin}});if(error)throw error;setPassword('');setMessage('Проверьте почту и подтвердите адрес по ссылке.')}
    else {const {error}=await cloud.auth.resetPasswordForEmail(email,{redirectTo:window.location.origin});if(error)throw error;setMessage('Если адрес зарегистрирован, на него придёт письмо для восстановления.')}
  }catch(e){setMessage((e as Error).message)}finally{setBusy(false)}}
  return <section className="theory-card"><h2>Аккаунт и синхронизация</h2><p role="status">{info.status}</p>{!cloud?<p>Облачный сервер пока не подключён. Код регистрации, подтверждения почты, восстановления и синхронизации подготовлен; сейчас данные остаются на этом устройстве.</p>:info.session&&!info.recovering?<><p>Вы вошли: {info.session.user.email}</p><div className="chip-row"><button className="primary-button" onClick={()=>void syncNow()}>Синхронизировать</button><button className="chip" onClick={()=>void signout()}>Выйти</button><button className="chip" onClick={()=>{try{if(currentOwner()!=='guest'){persistEvents(readEvents('guest'));setMessage('Локальные материалы и ответы добавлены в ваш аккаунт.')}}catch(e){setMessage(String(e))}}}>Перенести локальный прогресс в аккаунт</button></div></>:<form className="exercise-form" onSubmit={submit}>{!info.recovering&&<div className="chip-row">{(['login','signup','reset'] as const).map((m,i)=><button type="button" className={mode===m?'chip active':'chip'} key={m} onClick={()=>setMode(m)}>{['Вход','Регистрация','Забыли пароль?'][i]}</button>)}</div>}{!info.recovering&&<label>Email<input required type="email" autoComplete="email" value={email} onChange={e=>setEmail(e.target.value)}/></label>}{(mode!=='reset'||info.recovering)&&<label>{info.recovering?'Новый пароль':'Пароль'}<input required minLength={8} type="password" autoComplete={mode==='login'?'current-password':'new-password'} value={password} onChange={e=>setPassword(e.target.value)}/></label>}<button className="primary-button" disabled={busy}>{busy?'Подождите…':info.recovering?'Сохранить пароль':'Продолжить'}</button></form>}<p role="status">{message}</p></section>
}
