import { useEffect, useMemo, useRef, useState } from 'react'
import JSZip from 'jszip'
import { commit, useStudy } from './store'
import type { Book } from './core'
const sample:Book={id:'sample',title:'りんご · Пробный текст',description:'Короткий демонстрационный текст. Полный учебник будет добавлен после технической части.',text:'青森県はりんごの産地として有名です。\n\n青森県は、夏が涼しく、りんごの栽培に適した気候です。春に花が咲き、秋になると実が赤くなります。\n\n収穫されたりんごは、日本中の店へ運ばれます。旬のりんごは甘く、香りもとてもいいです。'}
type Result={id:string;forms:string[];reading:string;meanings:string[];lang:string;matched:string}
export default function Books(){
  const state=useStudy(),[bookId,setBookId]=useState<string|null>(null),[reading,setReading]=useState(false),[position,setPosition]=useState(0),[query,setQuery]=useState(''),[results,setResults]=useState<Result[]>([]),[message,setMessage]=useState(''),[error,setError]=useState(''),[loading,setLoading]=useState(false)
  const worker=useRef<Worker|null>(null),request=useRef(0),input=useRef<HTMLInputElement>(null)
  const books=[sample,...state.books],book=books.find(b=>b.id===bookId)
  const paragraphs=useMemo(()=>book?.text.split(/\n+/).filter(t=>t.trim())||[],[book?.text])
  const segmenter=useMemo(()=>new Intl.Segmenter('ja',{granularity:'word'}),[])
  const pageSize=6,pages=Math.max(1,Math.ceil(paragraphs.length/pageSize))
  useEffect(()=>()=>worker.current?.terminate(),[])
  function lookup(word:string){setQuery(word);setMessage('');setResults([]);setLoading(true);setError('');if(!worker.current){worker.current=new Worker('./dictionary-worker.js');worker.current.onerror=()=>{setLoading(false);setError('Не удалось запустить словарь. Обновите страницу.')};worker.current.onmessage=e=>{if(e.data.id!==request.current)return;setLoading(false);if(e.data.error)setError(e.data.error);else setResults(e.data.results)}}worker.current.postMessage({id:++request.current,word})}
  async function importBook(file:File){setError('');try{if(file.size>20*1024*1024)throw Error('Максимальный размер — 20 МБ. Разделите большую книгу на части.');let text='',title=file.name.replace(/\.[^.]+$/,'')
    if(file.name.toLowerCase().endsWith('.epub')){const zip=await JSZip.loadAsync(file),parser=new DOMParser();const container=zip.file('META-INF/container.xml');if(!container)throw Error('Не найдено описание EPUB');const c=parser.parseFromString(await container.async('text'),'application/xml');const opf=c.querySelector('rootfile')?.getAttribute('full-path');if(!opf||!zip.file(opf))throw Error('Неверный EPUB');const pkg=parser.parseFromString(await zip.file(opf)!.async('text'),'application/xml');title=pkg.getElementsByTagNameNS('*','title')[0]?.textContent||title;const base=opf.includes('/')?opf.slice(0,opf.lastIndexOf('/')+1):'';const items=new Map([...pkg.getElementsByTagName('item')].map(i=>[i.getAttribute('id'),i.getAttribute('href')||'']));const chapters=[];let size=0
      for(const ref of pkg.getElementsByTagName('itemref')){const href=items.get(ref.getAttribute('idref'));if(!href)continue;const path=decodeURIComponent(new URL(href,'https://epub.local/'+base).pathname.slice(1));const item=zip.file(path);if(!item)continue;const html=await item.async('text');size+=html.length;if(size>1_000_000)throw Error('Текст EPUB слишком большой для текущего локального хранилища. Разделите книгу.');const doc=parser.parseFromString(html,'text/html');doc.querySelectorAll('script,style,rt,rp').forEach(x=>x.remove());chapters.push([...doc.querySelectorAll('p,h1,h2,h3')].map(p=>p.textContent).join('\n\n')||doc.body.textContent||'')}text=chapters.join('\n\n')
    }else if(/\.(txt|md)$/i.test(file.name))text=await file.text();else throw Error('Пока поддерживаются TXT и EPUB. Сканы PDF сначала нужно распознать.')
    if(!text.trim())throw Error('В файле не найден текст');if(text.length>1_000_000)throw Error('Слишком большой текст. Разделите книгу на части.')
    const b:Book={id:crypto.randomUUID(),title,description:'Личная книга',text};commit('book',b);setBookId(b.id);setReading(false)
  }catch(e){setError(String(e))}finally{if(input.current)input.current.value=''}}
  function turn(next:number){if(!book)return;const p=Math.max(0,Math.min(next,pages-1));try{commit('bookmark',{id:book.id,position:p});setPosition(p);window.scrollTo(0,0)}catch(e){setError(String(e))}}
  function saveWord(result:Result){try{const id=`book-${bookId}-${result.id}`;commit('word',{id,lesson:0,written:result.forms[0],reading:result.reading,meanings:result.meanings,examples:[],note:`Книга: ${book?.title}`,due:new Date().toISOString(),interval:0,bookId});setMessage('Добавлено в список книги. Изучение доступно в карточках слов.')}catch(e){setError(String(e))}}
  return <><input ref={input} type="file" accept=".txt,.md,.epub" hidden onChange={e=>{if(e.target.files?.[0])void importBook(e.target.files[0])}}/>
    {!book?<><div className="page-heading"><span>ЛИЧНАЯ БИБЛИОТЕКА</span><h1>Книги</h1><p>Перевод по нажатию, поиск выделенной фразы и свой словарь каждой книги.</p></div><button className="primary-button" onClick={()=>input.current?.click()}>＋ Добавить TXT / EPUB</button><div className="book-grid">{books.map(b=><button className="book-card book-button" key={b.id} onClick={()=>{setBookId(b.id);setPosition(state.bookmarks[b.id]||0)}}><div className="book-cover"><strong>本</strong><small>日本語</small></div><div className="book-details"><h2>{b.title}</h2><p>{b.description}</p><span>Открыть книгу →</span></div></button>)}</div></>:!reading?<><button className="text-back" onClick={()=>setBookId(null)}>← Библиотека</button><section className="theory-card"><h1>{book.title}</h1><p>{book.description}</p><p>Страница {position+1} из {pages} · {Math.round((position+1)/pages*100)}%</p><button className="primary-button" onClick={()=>setReading(true)}>Читать</button><h2>Слова этой книги</h2>{state.words.filter(w=>(w as any).bookId===bookId).map(w=><p key={w.id}><ruby>{w.written}<rt>{w.reading}</rt></ruby> — {w.meanings.join('; ')}</p>)}{!state.words.some(w=>(w as any).bookId===bookId)&&<p>Сохраните слово во время чтения — оно появится здесь.</p>}</section></>:<><button className="text-back" onClick={()=>{setReading(false);setQuery('')}}>← К книге</button><div className="reader-tools"><b>{book.title}</b><button className="chip" onClick={()=>{const selected=window.getSelection()?.toString().trim();if(selected)lookup(selected);else setMessage('Выделите слово или фразу в тексте.')}}>Найти выделенное</button></div><article className="reader-page"><h1>{book.title}</h1>{paragraphs.slice(position*pageSize,(position+1)*pageSize).map((p,i)=><p key={i}>{[...segmenter.segment(p)].map((token,j)=>token.isWordLike?<button key={j} onClick={()=>lookup(token.segment)}>{token.segment}</button>:<span key={j}>{token.segment}</span>)}</p>)}</article><div className="reader-nav"><button disabled={position===0} onClick={()=>turn(position-1)}>← Назад</button><span>{position+1} / {pages}</span><button disabled={position>=pages-1} onClick={()=>turn(position+1)}>Далее →</button></div></>}
    {query&&<aside className="dictionary-pop"><button aria-label="Закрыть словарь" onClick={()=>{setQuery('');request.current++;setLoading(false)}}>×</button><form onSubmit={e=>{e.preventDefault();lookup(query)}}><label>Словарь<input value={query} onChange={e=>setQuery(e.target.value)}/></label><button className="add-word">Найти</button></form>{loading?<p>Загрузка словаря…</p>:results.length?results.map(r=><div className="dictionary-result" key={r.id}><h3>{r.matched}</h3><span>{r.reading} · {r.lang==='rus'?'русский':'английский'}</span><p>{r.meanings.join('; ')}</p><button className="add-word" onClick={()=>saveWord(r)}>＋ В слова книги</button></div>):<p>Запись не найдена. Попробуйте словарную форму или выделите слово целиком. Имена могут отсутствовать.</p>}<small>JMdict · EDRDG · CC BY-SA 4.0</small></aside>}<p role="status">{message}</p><p role="alert">{error}</p>
  </>
}
