import { useEffect, useState } from 'react'
import { Home, GraduationCap, Languages, PenLine, BookOpen, Edit3, BarChart3, Settings, Menu, X, Brain, Sparkles, ChevronRight, Cloud, UserRound } from 'lucide-react'
import { grammar, kanji, lessons } from './data'
import { allWords } from './exercises'
import { commit, currentOwner, getState, importLegacy, persistEvents, useStudy } from './store'
import { dayKey, dueKeys, streak, validEvent } from './core'
import { Cards, Practice } from './Study'
import { Japanese } from './Japanese'
import KanjiBoard from './KanjiBoard'
import Books from './Books'
import { UpdateSettings } from './UpdateSettings'

importLegacy()
const nav=[['home','Сегодня',Home],['lessons','Уроки',GraduationCap],['words','Слова',Brain],['grammar','Грамматика',Languages],['kanji','Кандзи',PenLine],['books','Книги',BookOpen],['editor','Редактор',Edit3],['progress','Прогресс',BarChart3],['settings','Настройки',Settings]] as const
function route(){const raw=window.location.hash.replace(/^#\//,'');return raw.includes('access_token=')?'settings':raw||'home'}
export default function App(){
  const state=useStudy(),[path,setPath]=useState(route),[menu,setMenu]=useState(false),[,tick]=useState(0)
  const cloudInfo={recovering:false,session:null as null|{user:{email:string}},ready:true,status:'Сохранено на устройстве · Альфа 0.2.0'}
  const [view,search='']=path.split('?'),params=new URLSearchParams(search)
  useEffect(()=>{const update=()=>setPath(route());window.addEventListener('hashchange',update);const timer=setInterval(()=>tick(n=>n+1),30000);return()=>{window.removeEventListener('hashchange',update);clearInterval(timer)}},[])
  useEffect(()=>{if(cloudInfo.recovering){window.location.hash='/settings';setPath('settings')}},[cloudInfo.recovering])
  function go(next:string){window.location.hash=`/${next}`;setPath(next);setMenu(false);window.scrollTo(0,0)}
  const due=dueKeys(state,'').length
  return <div className="app-shell"><aside className={menu?'sidebar open':'sidebar'}><div className="brand" onClick={()=>go('home')}><div className="brand-mark">日</div><div><strong>日本語</strong><span>личный курс</span></div></div><button className="close-menu" aria-label="Закрыть меню" onClick={()=>setMenu(false)}><X/></button><nav>{nav.map(([id,label,Icon])=><button key={id} className={view===id?'nav-item active':'nav-item'} onClick={()=>go(id)}><Icon size={19}/><span>{label}</span>{id==='home'&&due>0&&<span className="nav-badge">{due}</span>}</button>)}</nav><div className="sidebar-course"><div className="mini-label">Тестовый учебный блок</div><strong>中級日本語</strong><span>Материалы для проверки функций</span></div><div className="profile"><div className="avatar"><UserRound size={20}/></div><div><strong>{cloudInfo.session?.user.email||'Локальный профиль'}</strong><span><Cloud size={12}/>{cloudInfo.session?'Аккаунт подключён':'На этом устройстве'}</span></div></div></aside>{menu&&<button className="backdrop" onClick={()=>setMenu(false)} aria-label="Закрыть меню"/>}
    <main><header className="topbar"><button className="menu-button" aria-label="Открыть меню" onClick={()=>setMenu(true)}><Menu/></button><div className="mobile-title">日本語</div><div className="top-actions"><span className="sync-status">{cloudInfo.status}</span><span className="streak">{streak(state)} дн.</span></div></header><div className="page" key={`${currentOwner()}-${path}`}>
      {!cloudInfo.ready?<p>Загрузка профиля…</p>:view==='home'?<Dashboard go={go}/>:view==='lessons'?<Lessons go={go}/>:view==='lesson'?<Lesson id={Number(params.get('id')||1)} go={go}/>:view==='words'?<WordHome go={go}/>:view==='cards'?<Cards category={params.get('category')==='kanji'?'kanji':'word'} mode={params.get('mode')==='learn'?'learn':'due'} onClose={()=>go('home')}/>:view==='practice'?<Practice mode={params.get('mode')==='daily'?'daily':params.get('mode')==='demo'?'demo':params.get('mode')==='grammar-due'?'grammar-due':'practice'} filter={params.get('filter')||undefined} onClose={()=>go('home')}/>:view==='grammar'?<Grammar go={go}/>:view==='kanji'?<KanjiHome go={go}/>:view==='writing'?<KanjiBoard/>:view==='books'?<Books/>:view==='editor'?<Editor/>:view==='progress'?<Progress/>:view==='settings'?<SettingsPage/>:<Dashboard go={go}/>}
    </div></main></div>
}
function Heading({title,subtitle}:{title:string;subtitle:string}){return <div className="page-heading"><h1>{title}</h1><p>{subtitle}</p></div>}
function Dashboard({go}:{go:(s:string)=>void}){
  const state=useStudy(),today=dayKey(),reviewed=state.reviews.filter(r=>dayKey(new Date(r.at))===today).length,percent=state.goal?Math.min(100,reviewed/state.goal*100):0
  const tasks=[{label:'Слова',category:'word',subtitle:'Повторить изученную лексику',icon:<Brain/>},{label:'Кандзи',category:'kanji',subtitle:'Повторить значения и чтения',icon:<span>漢</span>},{label:'Грамматика',category:'grammar',subtitle:'Закрепить правила в упражнениях',icon:<Languages/>}]
  const daily=state.sessions[`daily-${today}`]
  return <><section className="welcome"><div><span className="eyebrow">{new Date().toLocaleDateString('ru',{weekday:'long',day:'numeric',month:'long'})}</span><h1>おかえりなさい</h1><p>Ваши повторения, новые темы и одна общая контрольная.</p></div>{state.goal>0&&<div className="goal-ring" style={{'--progress':`${percent*3.6}deg`} as React.CSSProperties}><div><strong>{reviewed}</strong><span>из {state.goal}</span></div></div>}</section>
    <section className="section-block"><div className="section-title"><div><span>ПО РАСПИСАНИЮ SRS</span><h2>Повторить сегодня</h2></div></div><div className="task-grid">{tasks.map(t=><button className="task-card" key={t.category} onClick={()=>go(t.category==='grammar'?'practice?mode=grammar-due':`cards?category=${t.category}&mode=due`)}><div className="task-icon">{t.icon}</div><div className="task-copy"><h3>{t.label}</h3><p>{t.subtitle}</p></div><div className="task-count">{dueKeys(state,`${t.category}:`).length}</div><ChevronRight/></button>)}<button className="task-card wide" onClick={()=>go('practice?mode=daily')}><div className="task-icon test-icon"><Sparkles/></div><div className="task-copy"><span>ОБЩАЯ КОНТРОЛЬНАЯ</span><h3>Ежедневный тест</h3><p>{daily?`${daily.answers.length} / ${daily.exercises.length} ответов`:'До 12 заданий: вчерашние уроки и трудные темы'}</p></div><ChevronRight/></button></div></section>
    <div className="chip-row"><button className="primary-button" onClick={()=>go('lessons')}>Изучить новый материал</button><button className="chip" onClick={()=>go('practice?mode=demo')}>Пробная контрольная по всем разделам</button><button className="chip" onClick={()=>go('settings')}>Настроить цель</button></div><p className="muted">По упражнению на каждое слово, правило и кандзи. Пробная контрольная не меняет SRS.</p>
  </>
}
function Lessons({go}:{go:(s:string)=>void}){return <><Heading title="Уроки" subtitle="Сейчас наполнен пробный первый урок. Остальные материалы добавим после технической части."/><div className="lesson-list">{lessons.map(l=><button className="lesson-row" key={l.id} onClick={()=>go(`lesson?id=${l.id}`)}><div className="lesson-number">{String(l.id).padStart(2,'0')}</div><div className="lesson-main"><h3>{l.title}</h3><p>{l.subtitle}</p></div><span>{l.id===1?'Пробный блок':'Пока без заданий'}</span><ChevronRight/></button>)}</div></>}
function Lesson({id,go}:{id:number;go:(s:string)=>void}){
  const state=useStudy(),lesson=lessons.find(l=>l.id===id)||lessons[0],words=allWords(state.words).filter(w=>w.lesson===id)
  return <><button className="text-back" onClick={()=>go('lessons')}>← Уроки</button><Heading title={lesson.title} subtitle={lesson.subtitle}/>{id!==1?<p>Материалы этого урока будут добавлены позже.</p>:<><div className="mode-grid"><button onClick={()=>go('words')}><div className="mode-symbol">語</div><h2>Слова</h2><p>{words.length} карточки. Отдельно: заучивание и ввод ответа.</p></button><button onClick={()=>go('grammar')}><div className="mode-symbol gold">文</div><h2>Грамматика</h2><p>{grammar.length} правила с теорией и практикой.</p></button><button onClick={()=>go('kanji')}><div className="mode-symbol red">漢</div><h2>Кандзи</h2><p>{kanji.length} иероглифа: карточки, ввод и письмо.</p></button></div><p>Начато элементов: {Object.keys(state.cards).filter(k=>state.reviews.some(r=>r.key===k&&r.lesson===id)).length}</p></>}</>
}
function WordHome({go}:{go:(s:string)=>void}){const state=useStudy();return <><Heading title="Слова" subtitle="Заучивание карточками и практика с ручным вводом — два отдельных режима."/><div className="chip-row"><button className="primary-button" onClick={()=>go('cards?category=word&mode=learn')}>Изучить новые слова</button><button className="chip" onClick={()=>go('cards?category=word&mode=due')}>Повторить по SRS ({dueKeys(state,'word:').length})</button><button className="chip" onClick={()=>go('practice?filter=word')}>Практика с вводом</button></div><div className="lesson-list">{allWords(state.words).map(w=><div className="lesson-row" key={w.id}><b className="japanese">{w.written}</b><p>{w.meanings.join('; ')}</p><span>{state.cards[`word:${w.id}`]?`Повтор: ${state.cards[`word:${w.id}`].due.toLocaleString('ru')}`:'Новое слово'}</span></div>)}</div></>}
function Grammar({go}:{go:(s:string)=>void}){const [selected,setSelected]=useState(0),point=grammar[selected];return <><Heading title="Грамматика" subtitle="Теория и упражнения с автоматической проверкой. Ошибки возвращают правило в SRS."/><div className="two-column"><div className="topic-list">{grammar.map((g,i)=><button className={selected===i?'selected':''} key={g.id} onClick={()=>setSelected(i)}><span>{i+1}</span><div><small>Урок {g.lesson}</small><b>{g.title}</b></div></button>)}</div><article className="theory-card"><h1>{point.title}</h1><p className="lead">{point.explanation}</p><div className="formula"><span>ПОСТРОЕНИЕ</span><strong>{point.formation}</strong></div>{point.examples.map((ex,i)=><div className="grammar-example" key={i}><Japanese text={ex.japanese}/><p>{ex.translation}</p></div>)}<button className="primary-button" onClick={()=>go(`practice?filter=grammar:${point.id}`)}>Перейти к упражнениям</button></article></div></>}
function KanjiHome({go}:{go:(s:string)=>void}){const state=useStudy();return <><Heading title="Кандзи" subtitle="Значения и чтения в карточках, затем проверка написания."/><div className="mode-grid"><button onClick={()=>go('cards?category=kanji&mode=learn')}><div className="mode-symbol">漢</div><h2>Изучить карточки</h2><p>Открыть чтения, значения и слова-примеры.</p></button><button onClick={()=>go('cards?category=kanji&mode=due')}><h2>Повторить по SRS</h2><p>{dueKeys(state,'kanji:').length} к повторению сейчас.</p></button><button onClick={()=>go('writing')}><div className="mode-symbol red">書</div><h2>Письменная доска</h2><p>Обводка, письмо по памяти, проверка черт.</p></button></div><div className="chip-row"><button className="chip" onClick={()=>go('practice?filter=kanji')}>Упражнения с вводом кандзи</button></div></>}
function Editor(){
  const state=useStudy(),[id,setId]=useState(''),[written,setWritten]=useState(''),[reading,setReading]=useState(''),[meanings,setMeanings]=useState(''),[note,setNote]=useState(''),[lesson,setLesson]=useState(1),[message,setMessage]=useState('')
  function select(value:string){setId(value);const w=allWords(state.words).find(w=>w.id===value);setWritten(w?.written||'');setReading(w?.reading||'');setMeanings(w?.meanings.join('; ')||'');setNote(w?.note||'');setLesson(w?.lesson??1)}
  function save(e:React.FormEvent){e.preventDefault();try{const old=allWords(state.words).find(w=>w.id===id);commit('word',{...old,id:id||crypto.randomUUID(),lesson,written:written.trim(),reading:reading.trim(),meanings:meanings.split(';').map(s=>s.trim()).filter(Boolean),examples:old?.examples||[],note,due:old?.due||new Date().toISOString(),interval:old?.interval||0});setMessage('Сохранено. Прогресс существующего слова сохранён.');select('')}catch(e){setMessage(String(e))}}
  return <><Heading title="Редактор слов" subtitle="Добавляйте и редактируйте слова. История повторений сохраняется."/><form className="editor-form" onSubmit={save}><label>Материал<select value={id} onChange={e=>select(e.target.value)}><option value="">＋ Новое слово</option>{allWords(state.words).map(w=><option key={w.id} value={w.id}>{w.written} — {w.meanings[0]}</option>)}</select></label><label>Урок<select value={lesson} onChange={e=>setLesson(Number(e.target.value))}><option value={0}>Личные материалы</option>{lessons.map(l=><option key={l.id} value={l.id}>{l.id}. {l.title}</option>)}</select></label><label>Слово в кандзи<input required value={written} onChange={e=>setWritten(e.target.value)}/></label><label>Чтение<input required value={reading} onChange={e=>setReading(e.target.value)}/></label><label>Значения через ;<input required value={meanings} onChange={e=>setMeanings(e.target.value)}/></label><label>Заметка<textarea value={note} onChange={e=>setNote(e.target.value)}/></label><button className="primary-button">Сохранить</button><p role="status">{message}</p></form></>}
function Progress(){const state=useStudy(),correct=state.reviews.filter(r=>r.grade>1).length;return <><Heading title="Ваш прогресс" subtitle="Здесь только реальные ответы этого профиля."/><div className="stat-grid"><div><span>Ответов</span><b>{state.reviews.length}</b></div><div><span>Вспомнили / верно</span><b>{state.reviews.length?`${Math.round(correct/state.reviews.length*100)}%`:'—'}</b></div><div><span>Начато элементов</span><b>{Object.keys(state.cards).length}</b></div><div><span>Серия дней</span><b>{streak(state)}</b></div></div><div className="theory-card"><h2>Расписание повторений</h2>{Object.entries(state.cards).map(([key,card])=><div className="grammar-example" key={key}><b>{key.startsWith('word:')?allWords(state.words).find(w=>`word:${w.id}`===key)?.written:key.startsWith('kanji:')?kanji.find(k=>`kanji:${k.id}`===key)?.character:grammar.find(g=>`grammar:${g.id}`===key)?.title}</b><p>{card.due.toLocaleString('ru')} · ответов: {card.reps} · забываний: {card.lapses}</p></div>)}{!state.reviews.length&&<p>Начните с карточек или упражнения.</p>}</div></>}
function SettingsPage(){
  const state=useStudy(),[message,setMessage]=useState('')
  async function backup(){try{const {exportBackup}=await import('./platform');await exportBackup(JSON.stringify({version:2,events:getState().events},null,2),`nihongo-${dayKey()}.json`);setMessage('Резервная копия подготовлена.')}catch(e){setMessage(String(e))}}
  return <><Heading title="Настройки" subtitle="Альфа работает без регистрации. Прогресс хранится на вашем устройстве."/>
    <UpdateSettings/>
    <section className="theory-card"><h2>Цель на день</h2><div className="goal-options">{[0,10,20,30].map(n=><button key={n} className={state.goal===n?'active':''} onClick={()=>commit('goal',{value:n})}><b>{n||'Без цели'}</b>{n>0&&<span>ответов</span>}</button>)}</div></section>
    <section className="theory-card"><h2>Резервная копия и перенос прогресса</h2><p>Для переноса на другое устройство сохраните этот файл и откройте его там. Установка обновления поверх приложения сохраняет ваши данные.</p><button className="primary-button" onClick={()=>void backup()}>Сохранить копию прогресса</button><label className="file-import">Восстановить из файла<input type="file" accept=".json" onChange={async e=>{const f=e.target.files?.[0];if(!f)return;try{if(f.size>25_000_000)throw Error('Файл слишком большой');const data=JSON.parse(await f.text());if(data.version!==2||!Array.isArray(data.events)||!data.events.every(validEvent))throw Error('Неверный формат резервной копии');persistEvents(data.events);setMessage('Сохранение объединено с текущими данными.')}catch(e){setMessage(String(e))}}}/></label><p role="status">{message}</p></section></>
}
